#pragma once

#define VIRTUAL_SLM_FACTOR 1

// Sets VIRTUAL_SLM_FACTOR to 1
#define ENABLE_COLOR_CGH 0
#if ENABLE_COLOR_CGH
#undef VIRTUAL_SLM_FACTOR
#define VIRTUAL_SLM_FACTOR 1
#endif // #if ENABLE_COLOR_CGH


#define IMAGE_WIDTH (1920*VIRTUAL_SLM_FACTOR)
#define IMAGE_HEIGHT (1080*VIRTUAL_SLM_FACTOR)
#define PIXEL_SIZE (8e-3 / VIRTUAL_SLM_FACTOR)