#pragma once

#define VIRTUAL_SLM_FACTOR 2


#define USE_GPU_FOR_CGH 1
#define ENABLE_OCCLUSION 0
// Sets VIRTUAL_SLM_FACTOR to 1
#define ENABLE_COLOR_CGH 1

#if ENABLE_COLOR_CGH
#undef VIRTUAL_SLM_FACTOR
#define VIRTUAL_SLM_FACTOR 1
#endif // #if ENABLE_COLOR_CGH


#define IMAGE_WIDTH (1920*VIRTUAL_SLM_FACTOR)
#define IMAGE_HEIGHT (1080*VIRTUAL_SLM_FACTOR)