#pragma once

#define VIRTUAL_SLM_FACTOR 8
//#define NUM_IMAGES 1


#define IMAGE_WIDTH  (1920 * VIRTUAL_SLM_FACTOR)
#define IMAGE_HEIGHT (1080 * VIRTUAL_SLM_FACTOR)
#define PIXEL_SIZE   (8e-3 / VIRTUAL_SLM_FACTOR)
